defaults:
  - base_config.yaml

experiment_name: SPEED_eval
pretrained_path: ckpts/speed.pt

# dataset args
dataset_name: DAVIS
dataset_args:
  DAVIS:
    data_dir: ${oc.env:VFI_DATASETS_ROOT,datasets}/DAVIS
  SNU_FILM:
    data_dir: ${oc.env:VFI_DATASETS_ROOT,datasets}/snu_film
  XTest:
    data_dir: ${oc.env:VFI_DATASETS_ROOT,datasets}/X4K1000FPS/test
    res: 4k

visualize: false
